### PR TITLE
fix : color coded stocks

### PR DESCRIPTION
**Pull request by CulturalProfessor**
image

### CODE REVIEW

**Comment by aryangupta701** [comment]
yaar inka thoda alignment bhi shi krdo

**Comment by aryangupta701** [comment]
shyd span ki trh td use krna pdega

**Comment by CulturalProfessor** [comment]
Screenshot from 2023-08-16 19-14-27
Screenshot from 2023-08-16 19-14-20

**Comment by aryangupta701** [comment]
nice

**Comment by aryangupta701** [comment]
thank you

**Review by aryangupta701 — APPROVED** [review]

**Pull request merged**
